---
projects_dir: 'projects'
projects:
  Icinga 2:
    git: 'https://github.com/Icinga/icinga2.git'
    ref: 'master'
    target: 'icinga2'
    docs_dir: 'doc'
  Icinga Web 2:
    git: 'https://github.com/Icinga/icingaweb2.git'
    ref: 'master'
    target: 'icingaweb2'
    docs_dir: 'doc'
  Director:
    git: 'https://github.com/Icinga/icingaweb2-module-director.git'
    ref: 'master'
    target: 'director'
    docs_dir: 'doc'
    category: 'Modules'
  Business Process:
    git: 'https://github.com/Icinga/icingaweb2-module-businessprocess.git'
    ref: 'master'
    target: 'businessprocess'
    docs_dir: 'doc'
    category: 'Modules'
